# adapted from:
# - https://github.com/SEMICeu/style-guide/blob/main/antora-playbook.yml
# - https://github.com/meaningfy-ws/model2owl-docs/blob/main/antora-playbook.yml

site:
  title: SEMIC Style Guide RDF Validator
  start_page: ROOT::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    snippet_length: 250

content:
  sources:
  - url: https://github.com/meaningfy-ws/semic-styleguide-rdf-validator
    branches: [ 'main' ]
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
