= Conceptual model conventions (UML)

[[sec:cmc-r1]]
== Conceptual model as single source of truth

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Conceptual model as single source of truth

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r1[CMC-R1]

|*Statement*

The UML conceptual model should be used as single source of truth.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r2]]
== Fixed UML interpretation

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Fixed UML interpretation

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r2[CMC-R2]

|*Statement:*

The UML conceptual model must have a fixed interpretation.
|===

*Checkable:* No

Informative rule on mapping between model elements.

[[sec:cmc-r3]]
== Element names and URIs

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Element names and URIs

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r3[CMC-R3]

|*Statement:*

All UML Element names should be fit for URI generation with clear namespace organisation.
|===

*Checkable:* No

Has overlap with https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r4[CMC-R4] in that only uppercase or lowercase resource names are allowed (PascalCase and camelCase). However, currently unimplementable due to the complex regular expression(s) required and an error with certain SHACL-SPARQL implementations, as reported on https://discord.com/channels/911006583067144212/911020976496586782/1204449907226845194[Discord].

[[sec:cmc-r4]]
== Case sensitivity and charset

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Case sensitivity and charset

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r4[CMC-R4]

|*Statement:*

All UML Element names are case-sensitive and shall follow the CamelCase convention.
|===

*Checkable:* No

Has overlap with https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r3[CMC-R3]. Enforcing CamelCase with a _regex_ match is hard and may not be able to be implemented directly/correctly and prone to be brittle. Rather, we have to indirectly check if no other characters are used for separation. We can of course check if classes start with an uppercase and properties lowercase. However, currently unimplementable due to the complex regular expression(s) required and an error with certain SHACL-SPARQL implementations, as reported on https://discord.com/channels/911006583067144212/911020976496586782/1204449907226845194[Discord].

[[sec:cmc-r5]]
== Namespaces and prefixes in element names

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Namespaces and prefixes in element names

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r5[CMC-R5]

|*Statement:*

Element names shall be organised by namespaces. Namespaces may be indicated through prefixes delimited by colon (:) character, forming qualified names.
|===

*Checkable:* No

Not the domain of shape validation (ensuring existence of prefixes for namespaces).

[[sec:cmc-r6]]
== Rich annotations through tags

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Rich annotations through tags

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r6[CMC-R6]

|*Statement:*

UML Tags can be conveniently used for annotating the Elements.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r7]]
== Explicit depiction of external dependencies

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Explicit depiction of external dependencies

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r7[CMC-R7]

|*Statement:*
The UML diagrams should depict how the developed model relates to external (reused) models.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r8]]
== Class inheritance

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Class inheritance

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r8[CMC-R8]

|*Statement:*

Ensure that the attributes and associations of a superclass apply to all its subclasses.
|===

*Checkable:* No

Informative rule on design principle.

[[sec:cmc-r9]]
== Abstract classes

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Abstract classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r9[CMC-R9]

|*Statement:*

Classes that are not intended to be instantiated directly can be marked as abstract.
|===

*Checkable:* No

Rule is primarily specific to UML; not applicable in OWL and has not been observed in practice with SHACL. However, the extended SHACL vocabulary https://datashapes.org/dash#abstract-classes[dash-abstract-classes] may be investigated in the future for potential applicability at the UML-OWL layer, which may then be translateable as shape validation rules.

[[sec:cmc-r10]]
== Attribute definition and usage

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Attribute definition and usage

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r10[CMC-R10]

|*Statement:*

UML Attributes shall be used to define properties taking simple datatype values. An attribute declaration should specify
its datatype and multiplicity whenever possible [https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r11[CMC-R11]].
|===

*Checkable:* No

Mostly UML-specific; domain and range are not allowed in the conventions so this would not be applicable. Value ranges are also not always specified in SHACL. That literal properties don't have object values, and vice versa, is the subject of a syntax checker.

[[sec:cmc-r11]]
== Multiplicity of attributes and connectors

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Multiplicity of attributes and connectors

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r11[CMC-R11].

|*Statement:*

The multiplicity of connectors and class attributes should be specified, indicating the minimum and maximum cardinality. The cardinality shall be as permissive as possible in Core Vocabularies and as restrictive as necessary in Application Profiles.
|===

*Checkable:* No

Mostly UML-specific; presence of `maxCount` cannot be validated because, if in UML the value `*` or `n` is specified, there is no restriction to be generated. Additionally, `minCount` is not consistently generated for `minimum=0`.

[[sec:cmc-r12]]
== Connector definition and usage

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Connector definition and usage

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r12[CMC-R12]

|*Statement:*

UML Connectors shall be used to define relations and properties taking non-atomic type values. A connector declaration should specify multiplicity whenever possible [https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r11[CMC-R11]].
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r13]]
== All elements are "public"

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* All elements are "public"

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r13[CMC-R13]

|*Statement:*

The visibility of all UML Elements should be "public".
|===

**Checkable:** No

Rule is UML-specific.

[[sec:cmc-r14]]
== Controlled lists as Enumerations

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Controlled lists as Enumerations

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r14[CMC-R14]

|*Statement:*

The controlled lists of values shall be referred to as UML Enumerations and specified whenever possible.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r15]]
== Partition the model into packages

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Partition the model into packages

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r15[CMC-R15]

|*Statement:*

Packages have no semantic value, but shall be used whenever possible to logically organise the model.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r16]]
== Diagram readability

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Diagram readability

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r16[CMC-R16]

|*Statement:*

UML class diagrams shall be organised for readability.
|===

*Checkable:* No

Rule is UML-specific.

[[sec:cmc-r17]]
== Element stereotypes

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Element stereotypes

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r17[CMC-R17]

|*Statement:*

Stereotypes do not have semantic or normative value. They shall be avoided in the conceptual models unless a good motivation, and a strong need is provided.
|===

**Checkable:** No

Rule is UML-specific.

[[sec:cmc-r18]]
== Datatype definition and usage

|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Datatype definition and usage

|{set:cellbgcolor: #f5f8fc}
*Identifier* https://semiceu.github.io/style-guide/1.0.0/gc-conceptual-model-conventions.html#sec:cmc-r18[CMC-R18]

|*Statement:*

We strongly recommend that only OWL 2 compliant datatypes are used.
The creation of custom datatypes shall be avoided.
|===

*Checkable:* No

Anything declared within standard namespaces (RDF(S)/XSD) is acceptable because no new (custom) definitions are introduced. This, however, raises the question of new datatypes defined within these standard namespaces, which is not easy to check.
