= Semantic conventions

[[sec:sc-r1]]
== Formal language choice
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Formal language choice
|{set:cellbgcolor: #f5f8fc}

*Identifier*  https://semiceu.github.io/style-guide/1.0.0/gc-semantic-conventions.html#sec:sc-r1[SC-R1]
.
|*Statement:*

The formal ontology shall be expressed in OWL 2.
|===

*Formal Ontology Expression in OWL 2 Shape*:

* A node shape targeting a dummy focus node with a custom SPARQL query that checks if there does NOT exist a statement with `rdf:type` (not mandated but good to have as this is always an implied assumption)

* A node shape targeting the focus node `owl:Ontology` with a restriction of minCount=1 and maxCount=1 on the inverse of the path `rdf:type` (there must exist exactly one instance of the target node)

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/only_owl_ontology.shacl.ttl[only_owl_ontology.shacl.ttl]

**Non-Compliance Message(s):**

* Violation of standard practice: Missing explicit type declaration

* Violation of SEMIC rule SC-R1: Missing OWL ontology declaration

**Non-Compliance Severity:** Violation

**Desired State:** There exists a named instance of the ontology (owl:Ontology statement)

[[sec:sc-r2]]
== Limited (OWL 2) expressivity
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Limited (OWL 2) expressivity
|{set:cellbgcolor: #f5f8fc}

*Identifier*  https://semiceu.github.io/style-guide/1.0.0/gc-semantic-conventions.html#sec:sc-r2[SC-R2]
.
|*Statement:*

The formal ontology shall be lightweight in its logical underpinning, focusing mainly on the concept declarations, generalisation axioms and annotations.
|===

This rule requires multiple SHACL shapes:

*No rdfs:domain or rdfs:range Declarations Shape*

A node shape targeting any subject of `rdf:type` with restrictions of maxCount=0 on the properties `rdfs:domain` and `rdfs:range`

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/no_domain_range_opt.shacl.ttl[no_domain_range_opt.shacl.ttl]


**Non-Compliance Message(s):**

* V Non-observance of SEMIC rule SC-R2: No expressions of property domain shall be used

* Non-observance of SEMIC rule SC-R2: No expressions of property range shall be used

**Non-Compliance Severity:** Warning

**Desired State:** No rdfs:domain or rdfs:range declaration exists on any resource


*Only OWL Resources Exist Shape*

A node shape targeting any subjects of `rdf:type` with a restriction on the property `rdf:type` having values only from the set {owl:Ontology, owl:Class, owl:DatatypeProperty, owl:ObjectProperty, owl:AnnotationProperty}

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/only_owl_resources.shacl.ttl[only_owl_resources.shacl.ttl
]


**Non-Compliance Message(s):**

* Violation of SEMIC rule SC-R2: Only limited OWL class and property declarations shall be used

**Non-Compliance Severity:** Violation

**Desired State:** Only OWL resources (instances declared to be one of the primary OWL types) exist


*Using only  rdfs:subClassOf and rdfs:subPropertyOf Shape*

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/only_owl_resources.shacl.ttl[only_owl_resources.shacl.ttl]

**Non-Compliance Message(s):**

*  Violation of SEMIC rule SC-R2: Only subsumption OWL class relations shall be used

* Violation of SEMIC rule SC-R2: Only subsumption OWL property relations shall be used

**Non-Compliance Severity:** Violation

**Desired State:** Only rdfs:subClassOf are used between classes and rdfs:subPropertyOf between properties

*Limited Expressions to Select Properties*

A _closed_ node shape (ignoring certain properties) targeting the class `sh:NodeShape` with several property shapes representing the limited set, with only the property path declared for each.

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/select_few_expressions.shacl.ttl[select_few_expressions.shacl.ttl]


**Non-Compliance Message(s):**

* Non-observance of SEMIC rule SC-R2: The ontology shall be limited to a select few expressions

**Non-Compliance Severity:** Info

**Desired State:** Expressions are limited to a select few properties

*Minimum Set of Ontology Header Properties Shape*
A node shape targeting the class `owl:Ontology` with a property restriction for each property from a predetermined set (combining what's mentioned in the conventions and what's used in ePO) and minCount=1, and corresponding datatype restrictions (`rdf:langString` for those expected to be language-tagged, `xsd:date` for dates, `sh:IRI` for IRIs and `xsd:string` otherwise.

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/min_ontology_header.shacl.ttl[min_ontology_header.shacl.ttl]

**Non-Compliance Message(s):**
Non-observance of SEMIC rule SC-R2: The ontology shall include a minimum header ({?property} <{?type}>)

**Non-Compliance Severity:** Warning

**Desired State:** A minimum set of ontology header properties exist

*No advanced OWL construct exists Shape*
A node shape targeting all subjects of `rdf:type` with a property restriction on an alternativePath list including all of the advanced OWL properties, and another similar shape with only the subsumption properties restricted to `sh:IRI` node kind (effectively forbidding use of blank nodes as values through those properties).
**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/no_advanced_definitions.shacl.ttl[no_advanced_definitions.shacl.ttl]

**Non-Compliance Message(s):**

*  Violation of SEMIC rule SC-R2: Advanced logical definitions shall not be used
* Violation of SEMIC rule SC-R2: Advanced logical definitions shall not be used (bNodes in subsumption)

**Non-Compliance Severity:** Violation

**Desired State:** No advanced OWL construct exists

[[sec:sc-r3]]
== Lexicalisation
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Lexicalisation
|{set:cellbgcolor: #f5f8fc}

*Identifier*  https://semiceu.github.io/style-guide/1.0.0/gc-semantic-conventions.html#sec:sc-r3[SC-R3]
.
|*Statement:*

The choice in handling the lexicalisation of concepts shall be clearly defined and consistently implemented.
|===

*Primary Lexicalisation Properties Shape*

A node shape targeting any subjects of `rdf:type` with restrictions of minCount=1 on the UNION of the properties {`rdfs:label`, `skos:prefLabel`} having a severity of WARNING

**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/min_one_lexicalisation_opt.shacl.ttl[min_one_lexicalisation_opt.shacl.ttl]

**Non-Compliance Message(s):**  Non-observance of SEMIC rule SC-R3: At least one lexicalisation label should exist

**Non-Compliance Severity:** Warning

**Desired State:** At least one of the two primary lexicalisation properties exist for any resource

*Cardinality Constraints on Lexicalisation Literals Shape*


**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/max_one_label.shacl.ttl[max_one_label.shacl.ttl]

**Non-Compliance Message(s):**

*  Violation of standard practice: More than one `skos:prefLabel` exists without a language tag
* Language {lang} has been used by {n} values (default SHACL message)
* Language {?lang} used more than once (default SHACL message)

**Non-Compliance Severity:** Violation

[[sec:sc-r4]]
== Reasoning assumption
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Reasoning assumption
|{set:cellbgcolor: #f5f8fc}

*Identifier*  https://semiceu.github.io/style-guide/1.0.0/gc-semantic-conventions.html#sec:sc-r4[SC-R4]
.
|*Statement:*

No reasoning capabilities shall be assumed.
|===

**Checkable:** NO

Informational rule, actionable by way of other rules (e.g. no advanced OWL features are to be used).

[[sec:sc-r5]]
== Circular definitions
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Circular definitions
|{set:cellbgcolor: #f5f8fc}

*Identifier*  https://semiceu.github.io/style-guide/1.0.0/gc-semantic-conventions.html#sec:sc-r5[SC-R5]
.
|*Statement:*

The data specification (semantic, conceptual, or shape) shall not use circular definitions.

|===

**Checkable:** NO

Most examples in this rule describe situations that are already restricted by other rules according to the conventions, e.g. usage of domain and range is not allowed, neither are OWL axioms like owl:equivalentClass. Only actionable example could be that about rdfs:subClassOf, but not sure how to implement self-reference in a shape (maybe DASH has something).

TABLE HERE FOR:

***Shape Description(s***
Shapes File, Shape Description(s), Non-Compliance Message(s), Non-Compliance Severity, Desired State
FEEL FREE TO REARRANGE AS YOU SEE FIT
<EXAMPLE LINK TO A SHAPE ON GITHUB e.g. https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/only_owl_ontology.shacl.ttl>

**Non-Compliance Severity:** Violation

**Desired State:** All lexicalisation literals have a cardinality of zero or one with or without a language tag


==== Shape definition(s):

**Shape Description(s)**


**Checkable:** Yes

**Shape File** : https://github.com/meaningfy-ws/semic-styleguide-rdf-validator/blob/main/shapes/owl/only_owl_resources.shacl.ttl[only_owl_resources.shacl.ttl]



**Non-Compliance Message(s):**


**Non-Compliance Severity:** Violation

**Desired State:**